Fix/native program
amehmeto/corpo-sano pull request #396
Opened 2022-05-03 04:32 UTC by erkambozan

2022-05-03 07:53 UTC, erkambozan commented
@dependabot rebase

2022-05-03 08:04 UTC, erkambozan commented
@dependabot rebase

2022-05-04 17:06 UTC, amehmeto requested changes

2022-05-04 17:06 UTC, amehmeto commented on native-front/src/create-program/mappers/program.mapper.ts
> +      workouts
Double check amk

2022-05-06 13:18 UTC, merged